// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANp7q9l7dSwItP1umytsrhfPIOwJLXiP0',
    appId: '1:544626936122:web:61ac73b1502dcf50f7a803',
    messagingSenderId: '544626936122',
    projectId: 'financiero-c62d9',
    authDomain: 'financiero-c62d9.firebaseapp.com',
    storageBucket: 'financiero-c62d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlc8B3cApnbcvjI37hm3bDKo5nLkwzE_4',
    appId: '1:544626936122:android:ab7ea1ac308d9bacf7a803',
    messagingSenderId: '544626936122',
    projectId: 'financiero-c62d9',
    storageBucket: 'financiero-c62d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLpGPgt60s9Wxelxszhp608cgGHJ7KcA',
    appId: '1:544626936122:ios:4be8137fcb7f85edf7a803',
    messagingSenderId: '544626936122',
    projectId: 'financiero-c62d9',
    storageBucket: 'financiero-c62d9.appspot.com',
    iosBundleId: 'com.example.gestionFinancieraPersonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLpGPgt60s9Wxelxszhp608cgGHJ7KcA',
    appId: '1:544626936122:ios:4be8137fcb7f85edf7a803',
    messagingSenderId: '544626936122',
    projectId: 'financiero-c62d9',
    storageBucket: 'financiero-c62d9.appspot.com',
    iosBundleId: 'com.example.gestionFinancieraPersonal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANp7q9l7dSwItP1umytsrhfPIOwJLXiP0',
    appId: '1:544626936122:web:86756a90af24af39f7a803',
    messagingSenderId: '544626936122',
    projectId: 'financiero-c62d9',
    authDomain: 'financiero-c62d9.firebaseapp.com',
    storageBucket: 'financiero-c62d9.appspot.com',
  );
}
